### PR TITLE
Merge Dev into Main for KMC 1.1 release

### PR DESCRIPTION
**Pull request by IbraheemYSaleh**

### CODE REVIEW

**Review by dccutrig — APPROVED** [review]
Approved  - might have some minor changes in the future. Holding off on tagging incase of minor updates.

**Review by rjbrown2 — APPROVED** [review]

**Comment by dccutrig** [comment]
@IbraheemYSaleh  Verifying we're ready to proceed with this merge?

**Comment by rjbrown6** [comment]
I think we're probably good to merge in.

**Comment by IbraheemYSaleh** [comment]
@dccutrig we should be ready. All dev work for this release is done to the best of my knowledge.

**Pull request merged**
