### PR TITLE
Added bug fix, and freed additional memory that should be being freed

### PR DESCRIPTION
**Pull request by rjbrown2**

### CODE REVIEW

**Comment by IbraheemYSaleh** [comment]
Also need to fix sa->ak_ref  string handling

**Review by IbraheemYSaleh — APPROVED** [review]

**Review by jlucas9 — APPROVED** [review]
Good catch!

**Review by szemerick — APPROVED** [review]
Reviewed all changes during a Team meeting.

**Review by szemerick — APPROVED** [review]
nice catch. reviewed.

**Pull request merged**
