### PR TITLE
AMMOSGH-96: Add Initial CAM support with pre-authenticated cookiefile

### PR DESCRIPTION
**Pull request by IbraheemYSaleh**
This implements basic CAM support per this ticket:
https://github.jpl.nasa.gov/ASEC/AMMOS-CryptoLib/issues/96

Caveats to Note:
1. We cannot unit test this in our github build tests since CAM functionality requires supporting infrastructure (IE an active CAM server and KMC Crypto Service instance protected with CAM)
2. CAM cookies passed in by client applications can be unique per apply/process security function call -- So the only correct way to do this is to alter the Crypto apply/process TC function calls to allow passing in these cookies. To maintain backwards compatibility, the old signature is kept and calls the new signature with a NULL value for the cookies.

### CODE REVIEW

**Comment by IbraheemYSaleh** [comment]
This also addresses this issue:
https://github.jpl.nasa.gov/ASEC/AMMOS-CryptoLib/issues/104

**Comment by IbraheemYSaleh** [comment]
Config code has been updated to use the new crypto_deep_copy_string() function to address the issue Robert ran into:
https://github.jpl.nasa.gov/ASEC/AMMOS-CryptoLib/issues/112
Which forces some of the downstream applications to be hacky with configuration string preservation... That should be fixed now.

**Review by rjbrown2 — APPROVED** [review]
Looks good to me.

**Review by jlucas9 — APPROVED** [review]

**Review by szemerick — COMMENTED** [review]
Reviewed

**Pull request merged**
